language: node_js
node_js:
  - "7"
env:
  - CXX=g++-4.8
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.1
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - sh test/demo-test-script.sh
cache:
  directories:
    - "node_modules"
  yarn: true